@startuml Add Booking (POST)

header Sample VacQ Sequence Diagram
footer Page %page% of %lastpage%
title "Add Booking (POST)"

participant "Client" as client
participant "<<javaScript>>\n:server" as server
participant "<<router>>\n:bookings" as routerBookings
participant "<<middleware>>\n:authMiddleware" as authMiddleware
participant "<<controllers>>\n:bookings" as controllersBookings
participant "<<model>>\n:Booking" as modelBooking
participant "<<model>>\n:Hotel" as modelHotel
database "<<MongoDB>>\n:bookings" as BookingsDatabase
database "<<MongoDB>>\n:hotels" as HotelsDatabase

client->server ++:req.post('/hotels/:hotelId/bookings')
server->routerBookings ++:app.use('/hotels/:hotelId/bookings',bookings)
routerBookings -> authMiddleware ++:Verify JWT
authMiddleware -> routerBookings: If JWT is valid
routerBookings -> controllersBookings ++:addBooking(req.body)
controllersBookings->modelBooking ++:create(req.body)
modelBooking ->BookingsDatabase ++: BookingSchema
BookingsDatabase --> modelBooking --: booking
controllersBookings->modelHotel ++:findById(req.params.hotelId)
modelHotel --> controllersBookings --:hotel
controllersBookings <-- modelBooking --:booking
controllersBookings->client --:response

@enduml
