digraph HotelBookingSystem {
    rankdir=LR; // Left to Right direction

    // Actors
    node [shape=actor];
    User [label="Hotel User"];
    Admin;


    // Use cases
    node [shape=rect];
    System [label="{Hotel Booking System
    node [shape=ellipse];
    ManageHotels [label="Manage Hotels"];
    ManageBookings [label="Manage Bookings"];
    SearchHotels [label="Search Hotels"];
    BookRoom [label="Book a Room"];
    ViewBooking [label="View Booking"];
    UpdateBooking [label="Update Booking"];
    CancelBooking [label="Cancel Booking"];
    ViewAllHotels [label="View All Hotels"];
    ViewHotelDetails [label="View Hotel Details"];
    Register;
    Login;
    GetUserDetails [label="Get User Details"];
    Logout}style="rounded,filled" fillcolor="#dddddd"];

    // Relationships
    User -> {SearchHotels BookRoom ViewBooking UpdateBooking CancelBooking ViewAllHotels ViewHotelDetails Register Login GetUserDetails Logout};
    Admin -> {ManageHotels ManageBookings SearchHotels ViewBooking UpdateBooking CancelBooking ViewAllHotels ViewHotelDetails Register Login GetUserDetails Logout};
}