@startuml
left to right direction
actor Admin as Admin
actor "Hotel User" as User

rectangle "Hotel Booking System" as System {
    usecase "Admin Functions" as AdminFunctions
    usecase "User Functions" as UserFunctions
}

User --> UserFunctions: "Performs\nUser Functions"
Admin --> AdminFunctions: "Performs\nAdmin Functions"

AdminFunctions --> System: (Manage Hotels)
AdminFunctions --> System: (Manage Bookings)
AdminFunctions --> System: (Search Hotels)
AdminFunctions --> System: (View Booking by Hotel ID)

UserFunctions --> System: (Search Hotels)
UserFunctions --> System: (Book a Room)
UserFunctions --> System: (View Booking)
UserFunctions --> System: (Update Booking)
UserFunctions --> System: (Cancel Booking)
UserFunctions --> System: (View All Hotels)
UserFunctions --> System: (View Hotel Details)
UserFunctions --> System: (Register)
UserFunctions --> System: (Login)
UserFunctions --> System: (Get User Details)
UserFunctions --> System: (Logout)

AdminFunctions --> System: (Create Hotel)
AdminFunctions --> System: (Update Hotel)
AdminFunctions --> System: (Delete Hotel)

AdminFunctions --> System: (View All Hotels)
AdminFunctions --> System: (View Hotel Details)
@enduml
